import type { Metadata } from "next";
import TheHeader from "./../components/TheHeader";
import TheFooter from "./../components/TheFooter";
import "./globals.css";

export const metadata: Metadata = {
  title: "My first work with Next",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <TheHeader />
        <main className="main">{children}</main>
        <TheFooter />
      </body>
    </html>
  );
}
